---
languageCode: "en-us"
title: "the breadblog"
baseURL: "https://www.ashander.info/breadblog/"
metaDataFormat: "yaml"
theme: "hugo_theme_robust"
params:
  AuthorName: "Jaime Ashander"
  Twitter: "@jaimedash"
  googleAnalyticsUserID: "UA-60354418-1"
  about: "post/start-it-up/"
taxonomies:
  category: "categories"
  ingredient: "ingredients"
ignoreFiles: "\\.xcf$"
canonifyURLs: true
...
